name : java maven app
on:
    push:
        branches:
            - main

permissions:
  checks: write        # ← needed to create check runs
  contents: read       # ← needed to read the repo
  pull-requests: write 

  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: get the code
              uses: actions/checkout@v4
            - name: packeing the code
              run: mvn package 
            - name: publish test results
              uses: EnricoMi/publish-unit-test-result-action@v2
              with:
                files: "**/target/surefire-reports/**/*.xml"
                comment_mode: always